### ISSUE TITLE
Warning emitted from Swift Package

### ISSUE THREAD

**Issue by Jake-Prickett** [Constructor-io/constructorio-client-swift#127]
Hello,

We observed that a warning is being emitted when consuming the constructor client as a Swift Package.

`
<Redacted>/checkouts/constructorio-client-swift/Package.swift The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 15.2.99.
`

---

Would it be possible to bump the Swift Package support up to 9.0? I can even make the change if necessary. This would silence a warning in all consumers of the Swift Package's project. 

Thanks!

**Comment by jjl014** [comment]
This should be resolved in [v2.5.3](https://github.com/Constructor-io/constructorio-client-swift/tree/v2.5.3)
