### ISSUE TITLE
constructorio-client-swift/AutocompleteClient Swift Package installation

### ISSUE THREAD

**Issue by neemanwa** [Constructor-io/constructorio-client-swift#135]
Trying to install only AutoCompleteClient with Swift package manager but that is prompting username and password. how to fix this?

Swift package manager url : https://github.com/Constructor-io/constructorio-client-swift/tree/master/AutocompleteClien
<img width="1076" alt="Screenshot 2022-04-18 at 6 53 55 PM" src="https://user-images.githubusercontent.com/103624938/163814721-561bd617-4eca-4636-bc00-60d7948bfa3a.png">
t

**Comment by jjl014** [comment]
That is very odd. It shouldn't require credentials to install the AutocompleteClient.

This issue is a bit stale so I'm going to close it, but please let us know if this is still an issue. Thanks!
