### ISSUE TITLE
Missing field in CIOBrowseResponse

### ISSUE THREAD

**Issue by carlosbanos85** [Constructor-io/constructorio-client-swift#139]
Hello! 

We identified one issue regarding a missing field in the `CIOBrowseResponse` object. 
The field is called `collection` and it is being returned as part of the `browse` request  for a query.

## Repro steps

In order to reproduce the issue it is required to trigger a `ConstructorIO.browse(forQuery:)` request with a filtered by _"collection_id"_:

```swift
let browseQuery = CIOBrowseQuery(
        filterName: "collection_id",
        filterValue: "....",
        filters: nil,
        page: 1,
        perPage: 30
)

ConstructorIO.browse(forQuery: browseQuery) { _ }
```

The response for the previous request would have the following high-level structure:
```json
{
    "response": {
        "result_sources": { ... },
        "facets": [ ... ],
        "groups": [ ... ],
        "results": [ ... ],
        "sort_options": [ ... ],
        "total_num_results": ...,
        "features": [ ... ],
        "collection": { 
            "id": "...",
            "display_name": "...",
            "data":  ...,
        },
    },
    "result_id": "........"
    "request": { ... }
}
```

The above response would be handled by the `BrowseResponseParser`, which reads the JSON object and returns a `CIOBrowseResponse`.

## Proposal

- Adding a new object for the collection part of the response:
i.e
```swift
public class CIOCollectionData: NSObject {
    public let id: String
    public let display_name: String
    public let data: ...

    init?(json: JSONObject?) {
        guard let json = json, let id = json["id"] as? String, let display_name = json["display_name"] as? String else {
            return nil
        }
        self.id = id
        self.display_name = display_name
    }
}
```
- Adding the collection object as an optional field in `CIOBrowseResponse` giving that the field is not being returned for all type of browse results:
```swift
public class CIOBrowseResponse {
    ...
    public let collection: CIOCollectionData?
}
```

- Adding to the `BrowseResponseParser` the additional decoder, and add the value to the CIOBrowseResponse initializer
```swift
    let collection: CIOCollectionData = CIOCollectionData(json: response["collection"])
    ....
    return CIOBrowseResponse(
        ....
        collection: collection
    )
```

## Additional notes

It's counterpart in Android SDK already includes the `collection` field in the `BrowseResponseInner.java`:

```java
public class BrowseResponseInner {
    ....
    @SerializedName("collection")
    private ItemCollection collection;
}
```

## References

- [BrowseResponseParser.swift](https://github.com/Constructor-io/constructorio-client-swift/blob/master/AutocompleteClient/FW/API/Parser/Browse/BrowseResponseParser.swift)
- [CIOBrowseResponse.swift](https://github.com/Constructor-io/constructorio-client-swift/blob/master/AutocompleteClient/FW/Logic/Result/Responses/CIOBrowseResponse.swift)
- [BrowseResponseInner.java](https://github.com/Constructor-io/constructorio-java/blob/master/constructorio-client/src/main/java/io/constructor/client/models/BrowseResponseInner.java)

**Comment by jjl014** [comment]
Support for this has been added in [v2.2.3](https://github.com/Constructor-io/constructorio-client-swift/releases/tag/v2.2.3)
