### ISSUE TITLE
Add `result` information to the SearchResponse.

### ISSUE THREAD

**Issue by ZackFalgout** [Constructor-io/constructorio-client-swift#175]
`result` data comes back in the overall response JSON from a search query, however this data isn't parsed by the `SearchResponseParser`.  It contains information such as `page` and `num_results_per_page` which would be useful in the implementation of pagination.  It would be great if `results` was parsed by the `SearchResponseParser` and at least the `page`, `num_results_per_page`, and `term` data was surfaced by the SDK.  Thanks!

**Comment by jjl014** [comment]
This should be resolved by https://github.com/Constructor-io/constructorio-client-swift/pull/176

Closing this issue. 👍
