### ISSUE TITLE
Add support for async await

### ISSUE THREAD

**Issue by chriskilpin** [Constructor-io/constructorio-client-swift#194]
We are currently implementing the SDK for an app we are working on. The app is using Swift concurrency via Async/Await. It would be nice if the SDK had support for this alongside closure based callbacks.

We are wrapping the SDK methods with withCheckedContinuation methods to bridge support. This isn't ideal.
https://developer.apple.com/documentation/swift/checkedcontinuation

```
public func trackBrowserResultsLoaded(filterName: String, filterValue: String, resultCount: Int, customerIDs: [String]?, resultID: String?) async throws {
    return try await withCheckedThrowingContinuation { continuation in
        constructorIO.trackBrowseResultsLoaded(filterName: filterName, filterValue: filterValue, resultCount: resultCount, customerIDs: customerIDs, resultID: resultID) { result in
            if let error = result.error {
                continuation.resume(throwing: error)
            }
            else if let _ = result.data {
                continuation.resume()
            }
        }
    }
}
```

**Comment by jjl014** [comment]
Hi @chriskilpin, thank you for sharing your feature request! While we don't have any immediate plans to add support for it, we appreciate the input! We'll discuss it with our product manager to explore the possibility of adding it to our roadmap in the future.

Closing this issue for now, but please feel free to open new issues or reach out to us on Slack. Your feedback is greatly appreciated!
